# Generated by Django 5.2.6 on 2025-10-19 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('aporte_necesario', models.TextField()),
                ('cantidad', models.IntegerField(default=0)),
                ('id_back_etapa', models.CharField(max_length=255, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ong_responsable', models.CharField(max_length=255)),
                ('id_back_ong', models.CharField(max_length=255, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('case_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ong_coolaboradora', models.CharField(max_length=255)),
                ('id_ong_coolaboradora', models.CharField(max_length=255, unique=True)),
                ('aporte', models.CharField(max_length=255)),
                ('es_total', models.BooleanField(default=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('fecha_compromiso', models.DateField(auto_now_add=True)),
                ('cumplido', models.BooleanField(default=False)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromisos', to='api_projectplanning.etapa')),
            ],
        ),
        migrations.AddField(
            model_name='etapa',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='api_projectplanning.project'),
        ),
    ]
