# Generated by Django 5.2.6 on 2025-10-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projectplanning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compromiso',
            old_name='etapa',
            new_name='etapa_cloud',
        ),
        migrations.RenameField(
            model_name='etapa',
            old_name='proyecto',
            new_name='proyecto_cloud',
        ),
        migrations.AddField(
            model_name='compromiso',
            name='id_etapa_back',
            field=models.CharField(default=123, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etapa',
            name='id_proyecto_back',
            field=models.CharField(default=123, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='id_back_proyecto',
            field=models.CharField(default=123, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
