# Generated by Django 5.2.6 on 2025-10-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projectplanning', '0002_rename_etapa_compromiso_etapa_cloud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromiso',
            name='id_etapa_back',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='compromiso',
            name='id_ong_coolaboradora',
            field=models.CharField(max_length=255),
        ),
    ]
