# Generated by Django 5.2.6 on 2025-10-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projectplanning', '0003_alter_compromiso_id_etapa_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='id_back_etapa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='id_proyecto_back',
            field=models.CharField(max_length=255),
        ),
    ]
