# Generated by Django 5.2.7 on 2025-10-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_projectplanning', '0004_alter_etapa_id_back_etapa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id_back_ong',
            field=models.CharField(max_length=255),
        ),
    ]
